# Generated by Django 2.2.3 on 2019-07-07 18:49

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20160728_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinksrelatedlink',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='footerlinksrelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='utils.FooterLinks'),
        ),
    ]
